[package]
name = "VideoTransform"
version = "0.1.0"

# Do NOT change the [[bin]] and [lib] sections
[[bin]]
name = "pipe"
path = "bin/pipe.rs"
[lib]
name = "algorithm"

[dependencies]
rustc-serialize = "0.3.19"
#algorithmia = "1.3.0"
algorithmia = { git = "https://github.com/algorithmiaio/algorithmia-rust", branch = "1.x" }
hyper = "0.9.10"
regex = "0.1.77"
lazy_static = "0.2.1"
wrapped_enum = "0.1.3"
rayon = "0.4.3"
uuid = { version = "0.2.3", features = ["v4"]}
either ="1.0.1"
time = "0.1"
